//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFinal2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class operacion
    {
        public int id_operacion { get; set; }
        public string concepto { get; set; }
        public int monto { get; set; }
        public System.DateTime fecha_op { get; set; }
        public int tipo { get; set; }
    
        public virtual tipo_op tipo_op { get; set; }
    }
}
